# argocd_create_application_playbook.yml
- name: Remove group from role
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: bitertech/argocd/samples/argocd_remove_policy_from_role.yml
      bitertech.argocd.group:
        api_url: "http://argocd.localhost/api/v1"
        token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJ2aWV3bmV4dDphcGlLZXkiLCJuYmYiOjE2OTUyMTMxNDEsImlhdCI6MTY5NTIxMzE0MSwianRpIjoidG9rZW4yIn0.rv-vb3e6jrmZcVzxR4vqC-CDET-JGU1QX9wRofSNxaE"
        project_name: "my-project"
        role_name: "my-new-role1"
        groups: 
          - "grupo1"
        status: "absent"
      register: result

    - name: Debug
      ansible.builtin.debug:
        var: result
